### ISSUE TITLE
Email doesn't work

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/dashboard#13]
After configuring the IMAP server (gmail) in personal settings,  it only displays a message "Extension missing: imap" in the dashboard where the mail is supposed to be. 

Nextcloud v12.0.1

**Comment by Erreur32** [comment]
Probably php7.0-imap (or php-imap)  packaged is missing:

`apt-get install php7.0-imap`

and Restart Apache after that.

**Comment by aproposnix** [comment]
Thanks @Erreur32  that worked.  Issue resolved.

**Comment by Babene03** [comment]
we use PHP7.1 but we have a problem, i can't install php7.1-imap.

> WARNING: the "php7.1-imap" package was deleted from this repository

https://www.ubuntuupdates.org/package/core/zesty/universe/proposed/php7.1-imap

**Comment by ashgoodman** [comment]
I have php7.2-imap installed and am getting the extension missing imap error

Will it only work on 7.1?
