### ISSUE TITLE
can't install dashboard

### ISSUE THREAD

**Issue by tuxpol** [nextcloud/dashboard#16]
hi everyone!
i'm trying to enable the dashboard on my nextcloud installation but i have this error
"App for id dashboard has a wrong app ID in info.xml:"
what can i do?
Thanks!
bye

**Comment by ChristophWurst** [comment]
Ref https://github.com/nextcloud/mail/issues/492#issuecomment-330829469

**Comment by MorrisJobke** [comment]
Fixed in https://github.com/nextcloud/server/pull/6586
