### ISSUE TITLE
Maybe disabling this app could be the right decision

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/dashboard#24]
This app does not seem to be maintained:
-  tickets are not closed (even the ones from Nextcloud developers like #3, #7, #10) 
- on the forum there are several negative posts (e.g: [Dashboard app abandoned?](https://help.nextcloud.com/t/dashboard-app-abandoned/27341) , [Dashboard alternatives?](https://help.nextcloud.com/t/dashboard-alternatives/22272) )

@jospoortvliet maybe it would be better to inactivate this app. It makes Nextcloud look unprofessional.

**Comment by stratege1401** [comment]
i ve just uninstalled it ... the nc_dashbord id dead too

**Comment by Spartachetto** [comment]
@daita given the recent work on this app and the projects about the future, maybe you could close this issue....

**Comment by daita** [comment]
I liked this issue :-)

**Comment by Spartachetto** [comment]
@daita I thinked a lot before writing it. 
At the time it seemed a reasonable proposal.
Now I think that a dashboard like the one you are trying to realize could be a major update in Nextcloud usability.

I have to thank you. You accepted this issue with huge professionality
