### ISSUE TITLE
Dashboard Design

### ISSUE THREAD

**Issue by Matze202** [nextcloud/dashboard#26]
1. Bei #app-content-wrapper fehlt mir folgendes:
> flex-wrap: wrap;

Erst nach dem manuellen Einfügen sieht die Auflistung vom Dashbord bei mir so aus, wie bei eurem Screenshot.

2. Beim Quota habe ich bei sehr kleiner Speichernutzung die Anzeige mehrzeilig. Dies konnte ich aktuell noch nicht selbst beheben.

**Comment by MichaSei** [comment]
Danke für den guten, aber leider nicht ganz so hilfreichen Tipp.

wo genau darf ich denn die Änderung eintragen?
welcher Datei in welchem Ordner wartet darauf?

**Comment by Matze202** [comment]
Ich hatte es nicht lange genutzt, weil ich es leider noch nicht als tauglich erachtet hatte.
Die Datei findest du in dem Ordner der App, wenn du es noch brauchst und absolut nicht findest, muss ich nochmal das auf einem Testserver drauf machen und mir es nochmal ansehen.

**Comment by daita** [comment]
Please use english language to report your issue

**Comment by Matze202** [comment]
@daita sorry my english is not good, deshalb bleibe ich lieber bei deutsch und wer nicht deutsch spricht, kann es per Translater übersetzen lassen, bevor ich hier nur das falsch übersetzte poste und keiner mich versteht.

**Comment by jancborchardt** [comment]
@Matze202 please then put it through Google Translate or similar before you report it. :) English is the regular language of the project, and we shouldn’t require every single person reading the issue to translate it.

**Comment by Matze202** [comment]
@jancborchardt Ich weiß, du verstehst mich auch auf deutsch und ich hätte es auch gar nicht melden brauchen, wenn es zuviel ist, dann macht es zu, haut  es in die Tonne und ich melde dann auch nichts mehr. 

Sorry, aber ich habe momentan wenig Zeit und kann mir somit nicht sonst wie lange den Kopf zu zermardern, denn ich veröffentliche nur höchst ungern (und nur, wenn mir selbst wirklich viel daran liegt) etwas in einer anderen Sprache, weil wir beide Wissen, was für nen Mist oft bei den elektronischen Übersetzern raus kommt. 

Ich Nutze diese Erweiterung außerdem nicht mehr, weil mich diese absolut nicht überzeugen konnte und wenn ich ehrlich bin, kam ich bisher auch ohne ihr gut aus und werde auch weiter damit zurecht kommen.

**Comment by jancborchardt** [comment]
@Matze202 geht auch freundlicher. Aber wenn du die Anwendung sowieso nicht mehr nutzt, kann die Issue ja zu.
