### ISSUE TITLE
Dashboard not displaying properly

### ISSUE THREAD

**Issue by hessercan** [nextcloud/dashboard#28]
Having an issue getting the dashboard to show up properly...

<img width="1436" alt="screen shot 2018-04-16 at 9 03 05 am" src="https://user-images.githubusercontent.com/24305438/38810633-5d67e520-4155-11e8-883c-6f59f5f56859.png">

**Comment by tuxedo-rb** [comment]
Hello,
take a look at our fork [https://github.com/tuxedocomputers/dashboard](https://github.com/tuxedocomputers/dashboard).
We tried to solve the most critical issues, at least for nextcloud v13.
We still work on some improvements, but the current version is operational.

Users with older installments of nextcloud are also welcome to check it out.
Until now i was too lazy to set up a 3rd testserver with a older versions of nextcloud.

**Comment by hessercan** [comment]
Thank you, works like a charm! Have you considered updating the nextcloud store? That’s where I enabled the original that didn’t work.
-- 
 <https://www.hessercan.com/>	
Mark Hesser
HesserCAN <https://www.hessercan.com/>
(814) 753-4431 <tel:8147534431>

**Comment by daita** [comment]
v5.0.0 is available on the appstore

**Comment by stratege1401** [comment]
Hello,

juste tested v5.0.0 on NC13.0.4

Displaying OK
Setup changes OK
Responsiveness on my smartphone lets say OK

Good work !

**Comment by stratege1401** [comment]
@hessercan MAYBE YOU SHOULD REDACTED YOUR POST !!! YOUR PHONE NUMBER IS VISIBLE !!!

**Comment by hessercan** [comment]
Business phone number, not my personal.  That signature attaches to every email I send. Not worried about it, not sure why it was there though.
