### ISSUE TITLE
Advice/feedback on a descent way to add a setting panel for the next design of the dashboard:

### ISSUE THREAD

**Issue by daita** [nextcloud/dashboard#32]
@nextcloud/designers 

Hello,

I am rewriting from scratch the whole framework of the dashboard, the idea is to split each elements into Widgets, so the user can add/remove/move/resize each elements in his dashboard:

https://github.com/nextcloud/dashboard/tree/gridstack
(there is some instruction in README about the installation process of the app)

### The design issue
![selection_033](https://user-images.githubusercontent.com/1038617/41714426-8104c82a-7537-11e8-8210-a4521edb28c6.png)

You open the left panel using the Cog-Wheel.
When you open the left panel, it 'unlocks' the widgets so you can add/remove/move/resize them. When you close the left panel, the grid is saved and you cannot move the widgets anymore.

If you open the left panel and click on a Widget, it should display the settings for this widget in the left Panel.

There is actually 2 testing widget:

The first one (Lorem Ipsum) is just a bunch of text, but let's imagine it displays your last mails: you will need to setup the IMAP server/login/password. Open the left panel, add the widget, and click on the widget while the left panel is still opened. You should see some input field, **what do you think of this ?**

The second widget (Disk space) have no option available.

Note: This is a WIP and in the final version you should not be able to add more than one identical widget: when a widget is enabled in your dashboard, it should be removed from the 'Add new widget' list. Right now you can spam the same widget all over the dashboard, this is an _unwanted feature_.

**Comment by jancborchardt** [comment]
Let’s step back a bit, and first think of a design concept. :)

The use of the sidebar for configuration seems very strange. I would simply expect there to be a 3-dot icon on every widget, with an entry for "Edit settings". That would then either open a modal, or (more fancy) "rotate" the widget around and show its backside, where the settings are displayed.

There’s always an empty block with "Add new widget" on the right or bottom of the other widgets.

**Comment by daita** [comment]
I used the app-navigation to have the dashboard app working on small device (smartphone). I though also about the fancy rotation too, I am just afraid of the space needed by the settings for that widget. 

What do you mean by _modal / app-sidebar_ ? a panel that would open on the side of the widget ?

**Comment by jancborchardt** [comment]
@daita well, the space needed will be the same, no matter what container you use. But the navigation is not the proper element for this.

>  What do you mean by modal / app-sidebar ? a panel that would open on the side of the widget ?

Modal = modal like for the filepicker
app-sidebar = app-sidebar element like in Files or Talk or Calendar, on the right side.

**Comment by daita** [comment]
Yup, navigation is definitively not the right way.

Thanks for your feedback !

**Comment by jancborchardt** [comment]
Opened new issue for further feedback: https://github.com/nextcloud/dashboard/issues/33

Closing this hence :)
