### ISSUE TITLE
Design feedback on gridstack branch

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/dashboard#33]
For the record @daita, as discussed on IRC:

- [x] The top bar of each widget should be white, not blue.
- [x] The "widget-header-name" element should be a h2 instead of div
- [x] For every widget, use border-radius: var(--border-radius);
- [x] "Add widget" should not be only in the 3-dot-menu of every other widget, but a "Ghost/placeholder widget" like when you scroll all the way to the right in Github projects https://github.com/orgs/nextcloud/projects/6 and you see "+ Add column"

**Comment by daita** [comment]
Ok, @skjnldsv and I fulfilled the first 3 points, for the last one, you want this 'Add Widget' thing always visible (as long as there is new widget to be added) at the bottom right of the page ?

**Comment by daita** [comment]
https://cloud.artificial-owl.com/s/rpAYyP3mcTpMrRn

This would be the result

**Comment by jancborchardt** [comment]
Yup, that’s great, also with the dashed border! :) :+1:

**Comment by skjnldsv** [comment]
Yes, this looks very great :)
