### ISSUE TITLE
Database error on update

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/dashboard#38]
```
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_dashboard_settings AS SELECT FROM oc_dashboard_settings': SQLSTATE[HY000]: General error: 1 near "FROM": syntax error
```

@daita latest of both server and gridstack branch, make npm, and using SQLite.

**Comment by daita** [comment]
Hmm. yes. the issue is because you already used the branch before. Can you try to drop both table `oc_dashboard_settings` and `oc_dashboard_events` before performing the update ?

**Comment by jancborchardt** [comment]
Yeah, I dropped the tables. But could that error also be fixed, because I guess it’s not only happening to me, and others might just quit it.

**Comment by daita** [comment]
It is only happening because you upgraded from the branch version.
