### ISSUE TITLE
More useful widgets

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/dashboard#39]
The current widgets seem playful, but not particularly useful. There’s:
- Clock: not necessary because of the system clock
- Storage space: not really necessary either, as you get a notification when your space runs out
- Fortue quotes: … ;)

How about these instead:
- [x] 📅 The events of today in the Calendar (or the next 24 hrs) including weather of course
- [ ] ☑️ The tasks of today from the Tasks app
- [x] 🖺 List of most recent files with a quick way to open them and a "Share link" option for every one to quickly share
- [x] 🌟 List of favorite files/folders for quick access
- [x] 💌 List of unread and favorite emails
- [x] 😊 Favorite contacts for quick email or Talk
- [ ] 🖼️ Show a random picture from a specified folder (or whole Nextcloud by default), just for fun
- [ ] 🔀 Widget for http://keeporsweep.net ;D

Also we should then have a better default layout to have a nicer first run experience.

More input @nextcloud/designers?

**Comment by stefan-niedermann** [comment]
- :notebook: List of most recent notes with a quick way to open them in the Notes-App

**Comment by jancborchardt** [comment]
- ✍️ Direct note widget of a note of choice for quick note taking

**Comment by juliushaertl** [comment]
- Show recent activity
- Show cards from the deck app that are over or near due date

**Comment by daita** [comment]
Wow, wow, calm down !

Remember that widgets should be included in their relative apps, not in the Dashboard app !
For example, the list of recent files should be included in nextcloud/activity, but I like the Share options, however, it also means to open a right panel (which can be used by other widgets, like a quick-search to display results)

@juliushaertl : Can we work together on a widget for Deck, like I am providing a simple empty widget and you fill it ?

**Comment by jancborchardt** [comment]
@daita I know. ;) It’s not about the implementation detail but to have a design specification. We need to start with the user perspective of what people would need, instead of focusing on the technical side.

**Comment by daita** [comment]
- [ ] I will edit your messages to add checkbox

**Comment by daita** [comment]
@juliushaertl : made 2 empty widgets: https://github.com/nextcloud/deck/pull/540 - you should pull the last edit on the dashboard (2fb9147)

**Comment by Rello** [comment]
https://github.com/Rello/audioplayer/issues/328

**Comment by Spartachetto** [comment]
It could be interesting to have the "most used" something in the last period or overall.

For example: 
- files with most changes in the last three months / overall
- the tags used more often in the last three months / overall
- songs listened more often in the last three months  / overall
- ...

"Three months" is just a proposal for "recently". No idea if there is a conventional value for it

**Comment by darkjedeye** [comment]
how about enabling a feature that has a basic wysiwyg feel, that people can create their own widget with links to either their most used files, or to open any feature they have in nextcloud, sort of like "create a Dashboard Shortcut" type deal

**Comment by tuxedo-rb** [comment]
We worked on two additional Tasks sections for the old Dashboard (based on stable14 branch).
I published the code in our fork repo as a new branch named 'tasks_support'.
[https://github.com/tuxedocomputers/dashboard/tree/tasks_support](https://github.com/tuxedocomputers/dashboard/tree/tasks_support)

If someone want to reuse the code for a new Dashboard widget, just use it.

**Comment by zonky2** [comment]
- [ ] latest announcement
- [ ] generate a set of widgets as admin as default for the users

**Comment by MarkPartlett** [comment]
I recommend looking at iFrames for a quick win... https://youtu.be/3TzOXOcAV2I

**Comment by zonky2** [comment]
@MarkPartlett nice video... it´s possible to install this or you can share the source code?

**Comment by Spartachetto** [comment]
No idea about the technical solution.
What you (@MarkPartlett ) show is very interesting, it would be a huge added value (in my humble opinion) that the graphical representations (gauge, barplot, ...) could use Nextcoud internal data.
For example a barplot showing the frequence of the main tags, or the number of email per contact...

**Comment by MarkPartlett** [comment]
I'm working on making it a stand alone app using the dashboard app to display the widgets. The next stage is the request/transform to populate the JSON database records that control the java-script components within the widgets.  https://github.com/MarkPartlett/dashboardcharts is the code... I am working on the 'load demo data' button which also populates the DB for that user.

**Comment by Mannshoch** [comment]
I wish a kind of [Windirstat](https://windirstat.net) or [jdiskreport](http://www.jgoodies.com/freeware/jdiskreport/) to get an overview about the Disk usage of Users (admin) and my own directories.

It would be nice to change this stat to show most transferred data on the same directory based overview instead.

**Comment by steeve971** [comment]
Hi everyone,
I am a new user of Nextcloud. I just installed Dashboard on NC but there are only 3 widgets ?!
What about calendar events/new mails etc. as jancborchardt said ?

I am looking for a version of dashborad with all these widgets. Someone can help me please ?

Regards

**Comment by stefan-niedermann** [comment]
> Remember that widgets should be included in their relative apps, not in the Dashboard app !

@steeve971 this means that this dashboard app only works as a culmination - you need to ask the developer of the needed apps to make widgets (or ideally even contribute to one 🙂 ). Some of them are already linked in this thread.

**Comment by Botrap** [comment]
Hi i'm a new Nextcloud user too and was looking at  
https://github.com/markpartlett/dashboardcharts

Looks already fine but i was expecting dynamic ones or examples how to make that. @steeve971 something you're looking for too?

**Comment by steeve971** [comment]
Hi. Everyone, I am looking for widgets : last mails, calendar events, pendind tasks, announcements and contacts...
I am not familiair with coding or nextcloud. if needed, I am ready to pay a freelance to do that. It's for my small business. The dashboard is a good idea but after login, you don't have a large view on what's going on your nextcloud. it's pity. When an employee login, he must have directly a dashboard.
This is what I am expecting for.
Any ideas ? developer?
Best regards

**Comment by Spartachetto** [comment]
@steeve971 ,  @Botrap , have a look at https://github.com/nextcloud/server/issues/20930 
As you can see:

- This app will be discontinued (or it will find new maintainers)
- a new dashboard is already developed (but it could have another name)
- the new "dashboard" should provide the functionalities that @steeve971 is describing
- there is a strong possibility that this new "dashboard" will become the landing screen for the users
- the interactive graphs will be outside this new "dashboard" but they could still live if @MarkPartlett will find a technical solution

**Comment by jancborchardt** [comment]
With the new Dashboard which will come with Nextcloud 20, most of these widgets are actually implemented – I checked them off above. And lots of others are in development or have their own relevant issue, like:
- Analytics https://github.com/Rello/analytics/issues/61
- Social https://github.com/nextcloud/social/issues/983
- Bookmarks https://github.com/nextcloud/bookmarks/issues/869
- Notes https://github.com/nextcloud/notes/issues/587
- News https://github.com/nextcloud/news/issues/788
- Rainloop https://github.com/pierre-alain-b/rainloop-nextcloud/issues/208
- Probably more that I missed. :)
