### ISSUE TITLE
Nextcloud 14 RC1 + Dashboard 5.0.1: An exception occurred while executing 'SELECT lastval()': SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR: lastval is not yet defined in this session

### ISSUE THREAD

**Issue by morph027** [nextcloud/dashboard#44]
When trying to download and activate, it throws the following error:

```
An exception occurred while executing 'SELECT lastval()': SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR: lastval is not yet defined in this session
```

**Comment by Grimeton** [comment]
#metoo 

On Owncloud 14.0.1 

Anything I can hand you guys to help with this? Logs? Other stuff?

Cu

**Comment by tuxedo-rb** [comment]
Hello,
how Nextcloud handles INSERT queries for postgreSQL is part of [nextcloud/server](https://github.com/nextcloud/server) DBAL and their AdapterPgSql.

The abstract [Mapper.php](https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Db/Mapper.php) class calls for each INSERT operation `lastInsertId`, which always uses `SELECT lastval()` in [AdapterPgSql.php](https://github.com/nextcloud/server/blob/master/lib/private/DB/AdapterPgSql.php).
The files_antivirus App seems to have the same problem: [Error when inserting clean files with Postgresql](https://github.com/nextcloud/files_antivirus/issues/86).

**Comment by tuxedo-rb** [comment]
I reported the bug to the nextcloud/server issue board.
<https://github.com/nextcloud/server/issues/12465>
You could also override the insert method, how it @rullzer did for the files_antivirus App.
<https://github.com/nextcloud/files_antivirus/commit/c82de74f727513c702e403a25c36fea911460751>

**Comment by DrissiReda** [comment]
After trying to download & enable and this happens, I tried to click again and I got : 
`An exception occurred while executing 'INSERT INTO "oc_dashboard_settings"("id","key","value") VALUES(?,?,?)' with params [1, "show_activity", 1]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "oc_dashboard_settings_pkey" DETAIL: Key (id)=(1) already exists.`

**Comment by danielkesselberg** [comment]
15.0.1 is scheduled for 2019-10-01 and will ship a fix.

**Comment by Grimeton** [comment]
October 2019? Really?
