### ISSUE TITLE
l10n: There are no text strings to translate in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/dashboard#67]
Transifex lacks a lot of text strings that cannot be translated. Lack of translations results in an application not fully translated into the native language.

App:
Nextcloud 20.0.0 beta4
Dashboard  7.0.0

**Comment by rakekniven** [comment]
Hello @juliushaertl , 

is the dashboard part of default NC20 installation?
If so this would be a show stopper IMHO?

@Valdnet Can you add some screenshots?

**Comment by juliushaertl** [comment]
I'm not sure how translations are handled for apps inside of the server repo, @MorrisJobke do we need to setup anything additionally there?

**Comment by Valdnet** [comment]
@rakekniven This is what it looks like:

![obraz](https://user-images.githubusercontent.com/47037905/93595930-e042e300-f9b8-11ea-8e01-118180488c68.png)
![obraz](https://user-images.githubusercontent.com/47037905/93595985-f6e93a00-f9b8-11ea-8d60-aba0231e265a.png)
![obraz](https://user-images.githubusercontent.com/47037905/93596106-1ed89d80-f9b9-11ea-87ad-1596806ccc2a.png)
![obraz](https://user-images.githubusercontent.com/47037905/93596315-65c69300-f9b9-11ea-8b42-f365253ba423.png)
![obraz](https://user-images.githubusercontent.com/47037905/93596370-7c6cea00-f9b9-11ea-8e4b-b5bc84ef58aa.png)

**Comment by Valdnet** [comment]
To fully translate a Dashboard, you should also consider adding the following widgets to Transifex:
https://github.com/nextcloud/integration_zammad/issues/1
https://github.com/nextcloud/integration_discourse/issues/1
https://github.com/nextcloud/integration_github/issues/9
https://github.com/nextcloud/integration_gitlab/issues/4
https://github.com/nextcloud/integration_mastodon/issues/5
https://github.com/nextcloud/integration_reddit/issues/3
https://github.com/nextcloud/integration_twitter/issues/2

Sample widget:
![obraz](https://user-images.githubusercontent.com/47037905/93605191-b1cc0480-f9c6-11ea-91a6-dc43a9cf270d.png)

**Comment by MorrisJobke** [comment]
> I'm not sure how translations are handled for apps inside of the server repo, @MorrisJobke do we need to setup anything additionally there?

Apps inside the server repo are handled via https://github.com/nextcloud/server/blob/master/.tx/config - so new apps need to be added there. Most likely dashboard, status and weather.

**Comment by MorrisJobke** [comment]
> To fully translate Dashboard, you should also consider adding the following widgets to Transifex:
> [nextcloud/integration_zammad#1](https://github.com/nextcloud/integration_zammad/issues/1)
> [nextcloud/integration_discourse#1](https://github.com/nextcloud/integration_discourse/issues/1)
> [nextcloud/integration_github#9](https://github.com/nextcloud/integration_github/issues/9)
> [nextcloud/integration_gitlab#4](https://github.com/nextcloud/integration_gitlab/issues/4)
> [nextcloud/integration_mastodon#5](https://github.com/nextcloud/integration_mastodon/issues/5)
> [nextcloud/integration_reddit#3](https://github.com/nextcloud/integration_reddit/issues/3)
> [nextcloud/integration_twitter#2](https://github.com/nextcloud/integration_twitter/issues/2)

Yep - https://docs.nextcloud.com/server/19/developer_manual/app/view/l10n.html?highlight=transifex#setup-of-the-transifex-sync

**Comment by MorrisJobke** [comment]
Let me add all of them.

**Comment by MorrisJobke** [comment]
> Let me add all of them.

https://github.com/nextcloud/server/pull/22949

**Comment by MorrisJobke** [comment]
Should all appear this night :)

**Comment by MorrisJobke** [comment]
The server one is name "dashboard-shipped-with-server" in transifex.

**Comment by Valdnet** [comment]
@MorrisJobke Thanks a lot :wink:.
