### ISSUE TITLE
The page’s settings blocked the loading of a resource at inline (“script-src”).

### ISSUE THREAD

**Issue by shaynethiessen** [nextcloud/dashboard#74]
I get a content security policy error in the browsers console, along with a blank web page.

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

**Comment by Mikescops** [comment]
Ok folks, this is unrelated to this project, this issue should be addressed in nextcloud/server

This was fixed here: https://github.com/nextcloud/server/issues/23163

**Comment by shaynethiessen** [comment]
> Ok folks, this is unrelated to this project, this issue should be addressed in nextcloud/server
> 
> This was fixed here: [nextcloud/server#23163](https://github.com/nextcloud/server/issues/23163)

Thanks for the update!
